# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: mooncake
spec:
  selector:
    app: mooncake
  type: ClusterIP
  ports:
  - name: mooncake
    protocol: http
    port: 80
    targetPort: 8080
---
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mooncake
  labels:
    app:  mooncake
spec:
  selector:
    matchLabels:
      app: mooncake
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  mooncake
    spec:
      containers:
      - name:  mooncake
        image:  ghcr.io/brandoneto/mooncake:trunk
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
        ports:
        - containerPort:  8080
          name:  mooncake
